name: Docker Image Build und Push

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'  # Jeden Sonntag um Mitternacht UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Datum als Tag extrahieren
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Repository-Namen in Kleinbuchstaben umwandeln
        id: repo-name
        run: echo "repo=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Bei GitHub Container Registry anmelden
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx einrichten
        uses: docker/setup-buildx-action@v2

      - name: Image bauen und pushen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo-name.outputs.repo }}/srt-live-server:latest
            ghcr.io/${{ steps.repo-name.outputs.repo }}/srt-live-server:${{ steps.date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max